### ISSUE TITLE
Scroll thumb should not overrun track for negative scroll values

### ISSUE THREAD

**Issue by TedDriggs** [xobotyi/react-scrollbars-custom#10]
On Safari in the demo, scroll sideways on the "Custom Style" block with finger or trackpad, making sure to keep scrolling past the end of the content.

**Expected:** The thumb should be stopped at the end of the track. Best case, the length of the thumb shrinks proportional to the overrun, like the native iOS scroll bar.

**Observed:** The thumb keeps going past the end of the track.

**Comment by xobotyi** [comment]
Fixed: https://github.com/xobotyi/react-scrollbars-custom/commit/de093629cb780e7df8d8036145de08af295d7194
