### ISSUE TITLE
Adding only a vertical scrollbar while keeping the width dynamic

### ISSUE THREAD

**Issue by ranihorev** [xobotyi/react-scrollbars-custom#105]
**Do you want to request a _feature_ or report a _bug_?**

Ask a question / request a feature

**What is the current behavior?**

I'd like to add only vertical scrollbar while keeping the original width. The width should be dynamic and I'm not interested in horizontal scrollbar. Is there a way to do that? 

**If current behavior is a bug, please provide the steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have extra dependencies other than `react-scrollbars-custom`. Paste the link to your [JSFiddle](https://jsfiddle.net) or [CodeSandbox](https://codesandbox.io) example below:**

**What is the expected behavior?**

**Which versions of `react-scrollbars-custom`, React, and which browser / OS are affected by this issue? Did this work in previous versions of `react-scrollbars-custom`?**

4.0.12

**Comment by xobotyi** [comment]
Use a `translateContentSizeXToHolder`.  
You can find out more about it in readme.

**Comment by ranihorev** [comment]
Thanks!
