### ISSUE TITLE
elementRef warning in native

### ISSUE THREAD

**Issue by jnthnwn** [xobotyi/react-scrollbars-custom#106]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
React gives the following warning when passing the `native` prop to react-custom-scrollbars.

```Warning: React does not recognize the `elementRef` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `elementref` instead. If you accidentally passed it from a parent component, remove it from the DOM element.```

**What is the expected behavior?**
No warning.

**Which versions of `react-scrollbars-custom`, React, and which browser / OS are affected by this issue? Did this work in previous versions of `react-scrollbars-custom`?**
React 16.8.6
react-scrollbars-custom 4.0.16

**Comment by xobotyi** [comment]
Fixed in #107
