### ISSUE TITLE
Wird method declaration for OnScroll

### ISSUE THREAD

**Issue by LeopoldLerch** [xobotyi/react-scrollbars-custom#109]
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

Typescript not letting me use OnScroll in a typed way

**If current behavior is a bug, please provide the steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have extra dependencies other than `react-scrollbars-custom`. Paste the link to your [JSFiddle](https://jsfiddle.net) or [CodeSandbox](https://codesandbox.io) example below:**

I created my OnScroll-Response-Function with the following declaration:
```

    private onScrollFrame = (scrollposition: ScrollState, prevScrollState: ScrollState) => {
xxx
    }
```

however, i cannot transpile, as Typescript is expecting this weird delcaration:

`(property) onScroll?: ((event: React.UIEvent<HTMLDivElement>) => void) & ((scrollValues: ScrollState, prevScrollState: ScrollState) => void)`

Error Message is accordingly:

`Type '(scrollposition: ScrollState, prevScrollState: ScrollState) => void' is not assignable to type '((event: UIEvent<HTMLDivElement>) => void) & ((scrollValues: ScrollState, prevScrollState: ScrollState) => void)'.
  Type '(scrollposition: ScrollState, prevScrollState: ScrollState) => void' is not assignable to type '(event: UIEvent<HTMLDivElement>) => void'.`

I guess it is coming from that declaration , especially the "React.HTMLProps<T>"-Part of it:

`export declare type ElementPropsWithElementRefAndRenderer<T = HTMLDivElement> = React.HTMLProps<T> & {
    elementRef?: ElementRef<T>;
    renderer?: ElementRenderer<T>;
};`

**What is the expected behavior?**

Possibility to create a (typed) callbackFunction for the onScroll Event of the Scrollbar

**Which versions of `react-scrollbars-custom`, React, and which browser / OS are affected by this issue? Did this work in previous versions of `react-scrollbars-custom`?**

Current Version (4.0.16)

**Comment by gerainlotZS** [comment]
I also met this problem. Have you solved it？
