### ISSUE TITLE
Auto-height Feature?

### ISSUE THREAD

**Issue by mooman65** [xobotyi/react-scrollbars-custom#111]
Logging as a feature request as I'm not sure this is supported, but I would like a feature where I can just specify a maxHeight and only have the scrollbar appear should the content exceed that value.

**Describe the solution you'd like**
Something along the lines of: https://github.com/malte-wessel/react-custom-scrollbars/blob/master/docs/usage.md#auto-height

**Comment by xobotyi** [comment]
It is already implemented as a `translateContentSize*ToHolder` feature.
You can find more info about it in Readme.
