### ISSUE TITLE
Something wrong with RTLScroll, cannot read property 'insertBefore' of null

### ISSUE THREAD

**Issue by tadkondrat** [xobotyi/react-scrollbars-custom#115]
**What is the current behavior?**

I tried to import as default scrollbar component but code got fault. Before received this, i made few another components with scrollbar and everything was fine. But now something wrong...

> Uncaught TypeError: Cannot read property 'insertBefore' of null
    at shouldReverseRTLScroll (rsc.esm.js?d884:388)
    at Module.eval (rsc.esm.js?d884:909)
    at eval (rsc.esm.js:1899)
    at Module../node_modules/react-scrollbars-custom/dist/rsc.esm.js (application.js:8484)
    at __webpack_require__ (application.js:69)
    at eval (CardsList.tsx:10)
    at Module../webpack/app/Payment/View/Cards/CardsList.tsx (application.js:14944)
    at __webpack_require__ (application.js:69)
    at eval (index.tsx:9)
    at Module../webpack/app/Payment/View/Cards/index.tsx (application.js:14980)

My app code:

import Scrollbar from 'react-scrollbars-custom';
```javascript
 return (
  <Scrollbar
         maximalThumbSize={0}
        style={{ height: props.height - 42, flex: "1" }}
        disableTracksWidthCompensation
        minimalThumbSize={0}
        noScrollX
        trackYProps={{
          renderer: props => {
            const { elementRef, ...restProps } = props
            return (
              <span
                {...restProps}
                style={{ width: 0 }}
                ref={elementRef}
                className="trackY"
              />
            )
          }
        }}
>
</Scrollbar>
```

**A little about versions:**  
- _OS_: Mac OS
- _Browser (vendor and version)_: Google Chrome 76.0.3809.100 (Official Build) (64-bit)
- _React_: 16.8.4
- _`react-scrollbars-custom`_: ^4.0.17
- _Did this worked in the previous package version?_

**Comment by xobotyi** [comment]
Oo weird!
try thi sandbox: https://codesandbox.io/s/beautiful-haze-x4p0t is there errors?

**Comment by tadkondrat** [comment]
@xobotyi No errors now

**Comment by xobotyi** [comment]
>_>

**Comment by xobotyi** [comment]
@tadkondrat i'm releasing v4.0.18 now - try to use it and report on any results please.

**Comment by tadkondrat** [comment]
@xobotyi Got right now same error but with appendChild. Look like document is not loaded when i'm tried to render component. My react app starting after DOM loaded event...
> Cannot read property 'appendChild' of null

**Comment by xobotyi** [comment]
@tadkondrat Could you watch what the line, `el.appendChild(child);` or `doc.body.appendChild(el);` ?

**Comment by tadkondrat** [comment]
@xobotyi  doc.body.appendChild(el)
I insert my scripts after body and now its work fine. 

Before 

```HTML
<html>
<scripts />
<body></body>
</html>

```

After 

```HTML
<html>
<body></body>
<scripts />
</html>

```

**Comment by xobotyi** [comment]
Shall i close?

**Comment by tadkondrat** [comment]
Sure
