### ISSUE TITLE
When using instance methods, content & thumb doesn't update

### ISSUE THREAD

**Issue by rosemarystanley** [xobotyi/react-scrollbars-custom#119]
**What is the current behavior?**
Scrolling methods don't seem to actuall work. When calling any of the scrolling instance methods `scrollToBottom` `scrollTo` `scrollToTop` (sometimes) the scroll state does update but the actual contents inside the the `Scrollbar` element don't. For example, when I click `button--down` the `scrollTop` updates but the actual contents don't move nor does the scroll thumb move. 

**Steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have extra dependencies other than `react-scrollbars-custom`. Paste the link to your [JSFiddle](https://jsfiddle.net) or [CodeSandbox](https://codesandbox.io) example below:**

https://codesandbox.io/s/amazing-kapitsa-i7t4p?fontsize=14

**What is the expected behavior?**
After calling `scrollTo` or `scrollToBottom` programmatically the UI elements would update as well.

**A little about versions:**  
- _OS_: Mojave 10.14.6
- _Browser (vendor and version)_: Chrome Version 76.0.3809.132 
- _React_: 16.9.0
- _`react-scrollbars-custom`_: 4.0.20
- _Did this worked in the previous package version?_ unknown. This is my first attempt using this library.

**Comment by xobotyi** [comment]
@rosemarystanley i was caused by your invalid use of the ref object.
instead of `this.scrollbar.scrollToBottom()` you should use `this.scrollbar.current.scrollToBottom()`
