### ISSUE TITLE
Doesn't work on touch devices

### ISSUE THREAD

**Issue by AlexTACru** [xobotyi/react-scrollbars-custom#121]
**Doesn't work touch move scoll bar on touch devices - scroll bar jumps to top**

I'm try get around this behavior with adding touchmove listener. But after setting needed scroll value scroll bar again jumps to top.
How i can prevent scroll bar jumps to top?

**Comment by xobotyi** [comment]
Thus it would pourly work with multitouch. But anyways it's better to make it work anyhow.
Thanks for investigation, i'll release the fix when i have some time.
