### ISSUE TITLE
getScrollBarWidth occasionally returns 100 when failing to calculate the width via clientWidth

### ISSUE THREAD

**Issue by yagottahavehart** [xobotyi/react-scrollbars-custom#123]
**What is the current behavior?**
New implementation of getScrollWidth causing occasional issues resulting in a margin-right of -100 set to the scrollbar, when something around 15-20 would be appropriate.

**Steps to reproduce/debugging/Suggestions**
Unfortunately, we've noticed this deep in our site & don't have a reliable way to reproduce it. The content in question is located within an iFrame and the though is that the width calculations are happening before it's fully mounted.

I believe it's related to the change in Commit: https://github.com/xobotyi/react-scrollbars-custom/commit/543bbd4313fb6968c000c151651e71fd842b1df4

Specifically, `scrollbarWidth = el.offsetWidth - el.clientWidth;` was replaced with `getScrollbarWidth._cache = 100 - el.clientWidth;` in this commit.

When stepping through, `el.clientWidth` occasionally returns 0 (instead of the expected 80/85), which worked previously because `el.offsetWidth` returned 0 as well, resulting in the fallback width of 20.

**Note:** putting a breakpoint after the `doc.body.appendChild(el)` gives the site enough time to load & the correct value is returned from `el.clientWidth`

Not sure the correct solution here to harden the automatic getScrollbarWidth, but a value of 0 for `el.clientWidth` does not seem like it should be respected and perhaps should result in the fallback

**A little about versions:**  
- _OS_: OSX 10.14.5 (18F132) (though have seen it across a couple versions)
- _Browser (vendor and version)_: Chrome Version 77.0.3865.90 (Official Build) (64-bit)

- _React_: 16.10.1
- _`react-scrollbars-custom`_: 4.0.20
- _Did this worked in the previous package version?_ Yes, 4.0.18

**Comment by xobotyi** [comment]
Weird =/ ill add a fallback for that case.
Ty for bugreport.

**Comment by yagottahavehart** [comment]
Thank you!

**Comment by xobotyi** [comment]
@yagottahavehart write here on any results pls.
