### ISSUE TITLE
Scroll doesn't work with a selectbox

### ISSUE THREAD

**Issue by eugene-ilyin** [xobotyi/react-scrollbars-custom#128]
**What is the current behavior?**

The list of options is not scrollable by mouse wheel

**What is the expected behavior?**

The list of options should be scrollable by mouse wheel

**A little about versions:**  
- _OS_: Ubuntu
- _Browser (vendor and version)_: Chrome 77
- _React_: 16.8.6
- _`react-scrollbars-custom`_: 4.0.16
- _`react-select`_: 3.0.8
- _Did this worked in the previous package version?_ I don't know, didn't try it before.

When I'm applying the Scrollbar on the list of items for selectbox, it appears but doesn't scrollable by mouse.
Here is some example https://codesandbox.io/s/material-demo-ygq40, similar logic works for https://www.npmjs.com/package/react-perfect-scrollbar, you can switch it in code quite easy, see into function MenuList.

I guess that it is related to binding of the event. Maybe because html which have to be scrolled is not exist in the initial moment. I don't know, maybe I need to call something to bind and event of scroll after the list appears?

Please, pay your attention that I use react-select for the component of the selectbox.

I will appreciate any help. Thanks in advance.

**Comment by xobotyi** [comment]
@eugene-ilyin in happens because `react-scroll` captures the scroll event, you have to pass the `captureMenuScroll={false}` to `Select` component

**Comment by eugene-ilyin** [comment]
@xobotyi yes, it works! Thank a lot!
