### ISSUE TITLE
Add .prettierrc file

### ISSUE THREAD

**Issue by TedDriggs** [xobotyi/react-scrollbars-custom#13]
This is a minor dev quality-of-life issue; the code formatting at the moment isn't standard and as a result any attempt to auto-format will try to change the entire `index.js` file. Adding a config for prettier and running auto-formatting would make it easier for others to contribute to the library.

**Comment by xobotyi** [comment]
Added in https://github.com/xobotyi/react-scrollbars-custom/commit/9c4bc35414bbdd172f3310635d233670e7653c81
