### ISSUE TITLE
Mouse wheel scroll doesn't work with react-select

### ISSUE THREAD

**Issue by Serjman91** [xobotyi/react-scrollbars-custom#133]
Hello! I'm trying to create select menu with react-scrollbars-custom, however, I ran into a problem that the menu does not respond to scrolling with the mouse wheel when using 'react-select' version 3.0.8. On version 3.0.4 everything works correctly, but this is not the actual version unfortunately.
Please tell me is the problem on your side or not? Thanks

Link to 'react-select' https://github.com/JedWatson/react-select

**Comment by xobotyi** [comment]
Solution been described in #128, it is on the `react-select`'s side

**Comment by Serjman91** [comment]
Thanks a lot!
