### ISSUE TITLE
mobileNative makes scroll native on desktop too

### ISSUE THREAD

**Issue by vashchukmaksim** [xobotyi/react-scrollbars-custom#135]
**What is the current behavior?**
If we add prop "mobileNative" it uses native scroll on both mobile AND desktop. But docs says: "As native but enables only on mobile devices (actually when the scrollbarWidth is 0)."

**Steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have extra dependencies other than `react-scrollbars-custom`. Paste the link to your [JSFiddle](https://jsfiddle.net) or [CodeSandbox](https://codesandbox.io) example below:**

**What is the expected behavior?**
Scroll stays custom on desktop.

**A little about versions:**  
- _OS_: Mac (NB: it seems to work on Windows!)
- _Browser (vendor and version)_: Chrome/Safari/Firefox
- _React_: 16.12.0
- _`react-scrollbars-custom`_:  4.0.21
- _Did this worked in the previous package version?_: 4.0.0 still not working

**Comment by xobotyi** [comment]
As it said there - `if browser's scrollbar is 0`.
MacOS has absolutely positioned scrollbars and thus their width is not determinable and has 0 value.

**Comment by vashchukmaksim** [comment]
@xobotyi  Thank you for the explanation! Closed.
