### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by andrey-karnaukhov** [xobotyi/react-scrollbars-custom#143]
I am getting an error when I am trying to use Draggable,

> Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Draggable which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node

The error is located inside the react-draggable library. They fixed this in the latest versions.

Solution:

Update react-draggable to the latest version

**Comment by michalbundyra** [comment]
@andrey-karnaukhov There is PR for that, but somehow it's not merged for a while already: https://github.com/xobotyi/react-scrollbars-custom/pull/137

**Comment by xobotyi** [comment]
Fixed @ v4.0.22

**Comment by michalbundyra** [comment]
@xobotyi after updating it does not work at all... 
I am getting the following error in console:

```
index.js:1 ./node_modules/react-scrollbars-custom/dist/rsc.esm.js
Attempted import error: 'cnb' is not exported from 'cnbuilder'.
```

**Comment by xobotyi** [comment]
@michalbundyra Weirdo..
Did it updated dependencies? check the cnbuilder version it should be `2.4.0`

**Comment by michalbundyra** [comment]
@xobotyi it was updated, but somehow it didn't work. I've installed again and restarted my npm build, and it's fine now... But the warning is now in other place - on loading the scrollbar:

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DraggableCore which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in div (created by ScrollbarThumb)
    in DraggableCore (created by ScrollbarThumb)
    in ScrollbarThumb (created by Scrollbar)
    in div (created by ScrollbarTrack)
    in ScrollbarTrack (created by Scrollbar)
    in div (created by Scrollbar)
...
```

**Comment by xobotyi** [comment]
Just built `gh-pages` which uses published version of this pages and it gone fine.

**Comment by xobotyi** [comment]
@michalbundyra
Well, its up to `react-dragable` developer. Anyways ive plattend to move away from that lib in v5

**Comment by michalbundyra** [comment]
@xobotyi I am not sure if it is only up to `react-dragable` developer, see:

https://github.com/STRML/react-draggable/blob/v4.4.2/lib/DraggableCore.js#L159-L171

**Comment by xobotyi** [comment]
@michalbundyra welp, looks like i have some work to do %)

**Comment by michalbundyra** [comment]
@xobotyi any chance you will be able to fix it "any time soon"? Thanks :)

**Comment by xobotyi** [comment]
@michalbundyra fix will be released today with v4.0.23

**Comment by michalbundyra** [comment]
@xobotyi Hi, I've just tried 4.0.23 and still getting the same warning.
Have you forgotten to uncomment the following line:

https://github.com/xobotyi/react-scrollbars-custom/blob/6d062ddef48fab745a846ec3d442cf3ca4c31755/src/ScrollbarThumb.tsx#L205

added in commit https://github.com/xobotyi/react-scrollbars-custom/commit/ce18883eae76d8ac3e834bad7235e596fcd70c7b#diff-9dba54ee7e1b2995024a171d7aadad9dR205
?

Thanks!

**Comment by xobotyi** [comment]
@michalbundyra \*facapalm.jpg\*
had an issue with tests and forgot to uncomment...

Couple of minutes and ill publish fix.

**Comment by xobotyi** [comment]
@michalbundyra fix is published.

**Comment by michalbundyra** [comment]
@xobotyi thanks a lot, works as expected now :)

Not sure only why there is no 4.0.24 release on github: https://github.com/xobotyi/react-scrollbars-custom/releases ?

Thanks again! 👍

**Comment by xobotyi** [comment]
@michalbundyra tags are not pushed yet

**Comment by quolpr** [comment]
I am using 4.0.27 and react-draggable 4.4.4 ( related and fixed https://github.com/react-grid-layout/react-draggable/issues/440 ) and still have this issue

![image](https://user-images.githubusercontent.com/7958527/146373273-b46bcf3c-4292-464c-9046-77eec3e3003d.png)

**Comment by quolpr** [comment]
https://github.com/react-grid-layout/react-draggable/pull/632
