### ISSUE TITLE
How can we make it work with react-css-modules

### ISSUE THREAD

**Issue by linecept** [xobotyi/react-scrollbars-custom#162]
**Is your feature request related to a problem? Please describe.**
When noDefaultStyles is used how can we make this component be used together with the react-css-modules? Additionally, what are the default styles that we need to style in order to fully customize the css of the scrollbar?

**Describe the solution you'd like**
It would be good if it would work with react-css-modules so we would just pass an external css file and that would style the component. The CSS file would be processed by webpack/babel thru react-css-modules

**Describe alternatives you've considered**
Manually discovering what the stylings are (for instance ScrollbarsCustom-ThumbX, create a scrollbar.css and pass it into the component where the Scrollbar is needed and bypassing Webpack/Babel processing; downside is that we loose prefixes and errors can occur)

**Comment by xobotyi** [comment]
I'm not using react-css-modules and won't make component depend on it.
If you can bring the support of it without breaking capability and adding extraneous dependencies - PR's are welcome.

**Comment by linecept** [comment]
I ended up writing my own based on this. https://levelup.gitconnected.com/build-on-hover-custom-scrollbar-in-react-d846194a7ea4
