### ISSUE TITLE
What are the default styles that we need to style in order to fully customize the css of the scrollbar?

### ISSUE THREAD

**Issue by linecept** [xobotyi/react-scrollbars-custom#163]
**What is the current behavior?**

When the noDefaultStyles prop is passed the component is not rendered anymore. What do we need to do to work with the noDefaultStyles and what are the default styles that we need to style in order to fully customize the css of the scrollbar?

**What is the expected behavior?**
Passing in a scrollbar.css should make the styling of the scrollbar automatic. An example scrollbar.css should be provided

**A little about versions:**  
- _OS_: macOS
- _Browser (vendor and version)_: latest Chrome
- _React_: lastest react
- _`react-scrollbars-custom`_: latest
- _Did this worked in the previous package version?_ n/a

**Comment by xobotyi** [comment]
Component rendered and works, you just did not set dimensions for outmost container.
