### ISSUE TITLE
How do I change color of scrollbar?

### ISSUE THREAD

**Issue by windcloak** [xobotyi/react-scrollbars-custom#165]
The example does not say how I'm supposed to change the color of the scrollbar. 
Is there a code example for this?

**Comment by xobotyi** [comment]
Via css or `style` property of thumb element.
It is not in examples because it is basics of css/styling

**Comment by mdodge-ecgrow** [comment]
@windcloak  Example here: https://github.com/xobotyi/react-scrollbars-custom/issues/19#issuecomment-433807122

**Comment by mdodge-ecgrow** [comment]
FYI I am well versed in CSS.  But it took me a while to figure out how to do this as well.  More examples on the README would be appreciated.
