### ISSUE TITLE
Horizontal Scrollbar on the top of the div ratherthan on the bottom

### ISSUE THREAD

**Issue by GoChartingAdmin** [xobotyi/react-scrollbars-custom#175]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by GoChartingAdmin** [comment]
Is this project dead?

**Comment by xobotyi** [comment]
I've just missed the issue.

1) you've ignored issue template
2) just change horizontal scrollbar styles to be aligned to the top.

**Comment by GoChartingAdmin** [comment]
Apologies for ignoring the issue template.  Super Job!!!
