### ISSUE TITLE
React 17 support?

### ISSUE THREAD

**Issue by Devwulf** [xobotyi/react-scrollbars-custom#176]
Hello! Gotta say, you got a really great package here; it has been helpful to many of my projects so far! Thank you for it!

However, my newest project is currently using React 17, and it's a shame that this package doesn't support that version yet. Are you planning on supporting React 17 for this?

**Comment by xobotyi** [comment]
Js it only about peer dependencies version of this package? Sine react 17 has nothing new comparing to ract 16.

**Comment by Devwulf** [comment]
I think that seems to be the case. A simple addition to the dependency list of supported React versions should do the trick, since I can't install the package on React 17 properly.
