### ISSUE TITLE
User-provided styles should overrule default styles

### ISSUE THREAD

**Issue by TedDriggs** [xobotyi/react-scrollbars-custom#19]
Consider the following code:

```jsx
<Scrollbar trackVerticalStyle={{ background: 'rgba(0, 0, 0, 0)' }}><p>Hello world</p></Scrollbar>
```

In this case, I'd expect the track to render with no color, making it effectively invisible while still showing the thumb. However, the default style overrules my customization, which means it's impossible to change the color of the track without turning off _all_ default styles, which is overkill.

This can be addressed by flipping the order of the spreads in `index.js` so that the user provided styles - if they exist - are applied after the defaults but before the styles that are necessary for the library to work.

_This change shouldn't be hard, but I'm waiting for a decision on #18 before pushing the PR._

**Comment by SelaO** [comment]
I'm having the exact same problem, why add an api to change the className of the track and thumb but overwriting it with default element style? This makes this non-customizable. 

Disabling all the default styles makes it totally disappear too.

This is currently unusable.

**Comment by xobotyi** [comment]
Was unable to push changes due to github didn't worked for me somewhy.

**Comment by xobotyi** [comment]
https://github.com/xobotyi/react-scrollbars-custom/commit/912756313b0363a0cce9a652ec494619081f75e3

**Comment by SelaO** [comment]
@xobotyi Did you read what I wrote?

**Comment by TedDriggs** [comment]
@SelaO the `*ClassName` properties allow you to use stylesheets for pseudo-classes. You can also use `defaultStyles={false}` to disable the defaults for more stylistic control. 

As stated in the project readme, `react-scrollbars-custom` tries to minimize bundle size and dependencies, in part by using inline styles. You're free to use stylesheets instead, but you'll have to disable default styles to do so.

**Comment by SelaO** [comment]
BTW I'm on 2.2.6 and if I add `thumbVerticalStyle={{ background: 'red', color: 'red' }}` then the thumb get's height 0 and its transform stays at 0 too (it doesn't move when scrolling).

@TedDriggs @xobotyi

**Comment by xobotyi** [comment]
@SelaO can't reproduce what you're talkng about =/
```
<Scrollbar thumbVerticalStyle={{ background: 'red', color: 'red' }}>
</Scrollbar>
```
making the scrollbars just red:
![image](https://user-images.githubusercontent.com/6178739/47634201-b2a0e680-db61-11e8-9410-7680d0efc208.png)
