### ISSUE TITLE
Add option for track click to move one page towards pointer

### ISSUE THREAD

**Issue by TedDriggs** [xobotyi/react-scrollbars-custom#20]
In macOS and Ubuntu, clicking on the scrollbar track doesn't center the thumb at the click point. Instead, it moves the thumb one length toward the click point.

Other apps, like VS Code, have the jump-to-click point, so I don't think the behavior should be changed unconditionally. Instead, I'd propose adding a new prop, `trackClickBehavior`, which is `"jump" | "step"`, with `"jump"` being the default.

**Comment by xobotyi** [comment]
Been thinking about that too.
I'll implement it a bit later.

**Comment by xobotyi** [comment]
Released in v3.0.0
