### ISSUE TITLE
nativeScrollbars not functioning

### ISSUE THREAD

**Issue by petertait** [xobotyi/react-scrollbars-custom#22]
After putting nativeScrollbars prop onto `<Scrollbar nativeScrollbars  />` and setting it to true, I get the standard react warning:

`React does not recognize the 'nativeScrollbars' prop on a DOM element.`

Also, setting the prop to true doesn't change the scrollbars to be native, unless there is something I'm missing?

**Comment by xobotyi** [comment]
Sorry for long response.
This feature is experimental yet. all bugs will be fixed in v3 which is in progress.

**Comment by xobotyi** [comment]
Released in v3.0.0
