### ISSUE TITLE
v3.0 wrapperEl is not defined

### ISSUE THREAD

**Issue by thealjey** [xobotyi/react-scrollbars-custom#26]
v3.0 wrapperEl is not defined

that could be because I'm using a custom wrapperRenderer and maybe did something wrong

really cool rework btw!

**Comment by thealjey** [comment]
yep, you need to pass `elementRef` to the element
awesome
great implementation
just probably needs a mention in the docs
closing..

**Comment by xobotyi** [comment]
It is mentioned in [customisation doc](https://github.com/xobotyi/react-scrollbars-custom/blob/master/docs/CUSTOMISATION.md), but I've forgot to update the renderers example there.
