### ISSUE TITLE
doesn't work in vite (due to the use of global)

### ISSUE THREAD

**Issue by OneCyrus** [xobotyi/react-scrollbars-custom#269]
**What is the current behavior?**

adding this library in a vite project (or generally most modern frameworks) throws an exception with 'global is not defined'. this is due to the node global is not polyfilled in modern frameworks/bundlers.

**What is the expected behavior?**

no exception and the library can be used out of the box

**A little about versions:**  
- _OS_: Windows / Ubuntu
- _Browser (vendor and version)_: Chrome 103
- _React_: 17
- _`react-scrollbars-custom`_: 4.1.0
- _Did this worked in the previous package version?_ no

**Comment by xobotyi** [comment]
Should be fine in v4.1.1

**Comment by OneCyrus** [comment]
perfect, thank you! that works!
