### ISSUE TITLE
3.0 SSR regression

### ISSUE THREAD

**Issue by thealjey** [xobotyi/react-scrollbars-custom#28]
`getScrollbarWidth` crashes on Node.js because of `let doc = document;` on line 2

Pull request - #27

**Comment by xobotyi** [comment]
=) Just published 3.0.1 with that fix.
Sorry, rejecting pr.

**Comment by thealjey** [comment]
that was quick
awesome
thank you!

**Comment by xobotyi** [comment]
@thealjey actually not sure if change fixed the problem:
Due to i'm not an SSR user - it provides some `document` mock in global namespace?

**Comment by thealjey** [comment]
no, it does not
`global.document` will be undefined in node (will not throw because `global` is defined)
client side when compiled by webpack `global.document` will refer to `window.document`

**Comment by xobotyi** [comment]
I know about browser, just wondered how it work with SSR.
So the 3.0.2 is made like in your PR, and one more possible bug fixed;
