### ISSUE TITLE
Overlay vs block

### ISSUE THREAD

**Issue by fabiancook** [xobotyi/react-scrollbars-custom#30]
Is it possible to have the scrollbars be an overlay on top of the contained content, rather than taking up space from the container? 

This would be similar to how macOS handles scrollbars where the scrollbars are transparent (excluding the actual handle).

**Comment by xobotyi** [comment]
Sure, it's very easy:
```javascript
<Scrollbar wrapperProps = {{style: {margin: 0}}}/>
```
Almost every style is overridable.

**Comment by fabiancook** [comment]
Perfect, thanks

**Comment by thomasgassmann** [comment]
As of 2020, you might want to do it like this:

```javascript
<Scrollbar wrapperProps = {{style: {right: 0}}}/>
```

**Comment by xobotyi** [comment]
@thomasgassmann sadly but most _companies_ still have 1% rule. Meaning that if 1% of autdience is using IE it should be supported.
