### ISSUE TITLE
Detecting when scroll has reached the bottom

### ISSUE THREAD

**Issue by llamamoray** [xobotyi/react-scrollbars-custom#31]
I'm using react-custom-scrollbars in my project, but I have just come across this project and the performance looks great! I've tried to migrate to the library, but I've hit one snag:

I am trying to detect when the user has scrolled to the bottom of the panel using the `onScroll` prop. Is there enough information in the scrollValues object to work this out?

**Comment by thealjey** [comment]
`scrollTop === scrollHeight - clientHeight`

**Comment by llamamoray** [comment]
ah great - that's actually what I had but I've noticed that on a 4k screen in Windows 10 in Chrome there is some rounding issue with the `scrollTop` value, so I have to do this:

`scrollHeight - clientHeight === Math.round(scrollTop)`

**Comment by xobotyi** [comment]
@llamamoray the value is less or greater than `scrollHeight - clientHeight`?

**Comment by llamamoray** [comment]
@xobotyi it's less. In my example `scrollHeight - clientHeight = 3013`, and `scrollTop =  3012.888916015625`

**Comment by thealjey** [comment]
I was going to suggest `box-sizing: border-box;`, but this is apparently an os specific issue, and as such very peculiar.
Could you create a code pen or something demonstrating the issue, so I can try checking on a windows machine?

**Comment by llamamoray** [comment]
sure, is there a CDN version of the library, or a template I can use?

**Comment by llamamoray** [comment]
@xobotyi I added `className="native"` and can confirm that scrollTop is **not** a float. 

Using `scrollTop === scrollHeight - clientHeight` works without the rounding as a way to detect the scroll it at the bottom.

**Comment by xobotyi** [comment]
@llamamoray okay, i'll take a look when i have more time.

**Comment by xobotyi** [comment]
@llamamoray better late then never =)
Dig around that issue - actually the fact that you've got native integer scrollTop value was a luck. As for me, on chrome - made 175% system zoom (i have 1920x1200 screen) and got a float scrollTop val.

So, in order to save native behavior - nothing will be made with the component in this direction, leaving the rounding for developer.
