### ISSUE TITLE
Attempting to scroll with pointer on track should scroll content

### ISSUE THREAD

**Issue by TedDriggs** [xobotyi/react-scrollbars-custom#32]
In the native scrollbar, if you use the mouse wheel or trackpad scroll while the pointer is over the scroll panel's track, that scrolls. This doesn't happen in the component currently.

**Comment by xobotyi** [comment]
Actually i dont know how to make work this one.  
Scrollbar element is not a scroller kin, so scroller dowsn't receive `onmousewheel` event. I have an idea what possibly can work out, but wave no time yet to test it.

**Comment by xobotyi** [comment]
Feature added in 4.0.0-aplha
