### ISSUE TITLE
Styles cleanup

### ISSUE THREAD

**Issue by PeterKottas** [xobotyi/react-scrollbars-custom#33]
I was overriding some styles and noticed that these should/could be removed.
https://github.com/xobotyi/react-scrollbars-custom/blob/master/src/index.js#L39
https://github.com/xobotyi/react-scrollbars-custom/blob/master/src/index.js#L45 
Specifying both bottom/left and top/right should be enough (but maybe I am missing some edge case).

Btw, loving this lib. Was using react-custom-scrollbars before but came here as this is much neater. Wp!

**Comment by xobotyi** [comment]
>(but maybe I am missing some edge case)
you do =)
This made to not let scrollbars overlay eachother when both, vertical and horizontal shown.
If we are talking about generated CSS - `top:8px;right:0px;height:calc(100% - 16px)` and `top:8px;right:0px;bottom:8px` are pretty much the same, but first one theoretically a bit faster in terms of CSS.

>PS: thanks for appreciation

**Comment by PeterKottas** [comment]
Could have sworn I've seen left/top and right/bottom both defined when I glanced at it, must have been my styles overriding it ... Sry my bad.
