### ISSUE TITLE
Smooth Scroll

### ISSUE THREAD

**Issue by JCQuintas** [xobotyi/react-scrollbars-custom#35]
Is it possible to implement smooth scroll like in https://github.com/souhe/reactScrollbar?

That component is VERY inneficient and triggers a lot of re-renders, so we are dropping it in place of yours. But my designer would like to have smooth scrolling on some places because we are "emulating" a mobile app.

**Comment by tolgaergin** [comment]
agree with @xobotyi idea. `.ScrollbarsCustom-Scroller` div is the scrollable div. 
so you can pick `contentElement.parentElement`

```
this.scrollBar.contentElement.parentElement.scrollTo({
    behavior: 'smooth',
    left: 0,
    top: 0
});
```

**Comment by xobotyi** [comment]
@tolgaergin scroller can be accessed in a shorter way: `this.scrollBar.scrollerElement`

**Comment by JCQuintas** [comment]
Yeah that was how we implemented it, but thanks :)

**Comment by GaroGabrielyan** [comment]
useEffect(() => {
        if (scrollbarsRef.current.contentElement?.parentElement) {
            scrollbarsRef.current.contentElement.parentElement.scrollTo({
                top: 500,
                behavior: "smooth"
            });
        }
    }, []);
