### ISSUE TITLE
Expose getBoundingClientRect

### ISSUE THREAD

**Issue by JCQuintas** [xobotyi/react-scrollbars-custom#36]
Expose getBoundingClientRect or something similar that returns the entire component position. At the moment, since the component is a class, you can't get the rendered component position.

I had to encapsulate my component on a <div> so I can get it's relative position in my page.

**Comment by xobotyi** [comment]
Component exposes references to each generated HTMLElement, as described in [API](https://github.com/xobotyi/react-scrollbars-custom/blob/master/docs/API.md).

So you just have to do something like this:
```javascript
class MyComponent extends React.Component
{
    onComponentDidMount() {
        console.log(this.scrollbar.holderEl.getBoundingClientRect());
    }

    render() {
        return (
                <Scrollbar ref={ ref => this.scrollbar = ref } />
        );
    }
}
```
