### ISSUE TITLE
ScrollTo x and y are inverted

### ISSUE THREAD

**Issue by JCQuintas** [xobotyi/react-scrollbars-custom#38]
As the title says, scrollTo is documented as scrollTo(x, y) but in the code its at

```
scrollTo(y, x) {
        this.contentEl.scrollTop = y;
        this.contentEl.scrollLeft = x;

        return this;
}
```

https://codesandbox.io/s/1ykjml8xxl

**Comment by JCQuintas** [comment]
centerAt has the same issue

**Comment by xobotyi** [comment]
Yep, mistake in the docs.

**Comment by tonypig93** [comment]
Please update the docs, thanks

**Comment by xobotyi** [comment]
@tonypig93 in 3.2 it will be like in docs now, to maximally correspond to browser's API (where x coord goes first).
3.2 will be published in closest 2 weeks.
