### ISSUE TITLE
Momentum missing on mobile

### ISSUE THREAD

**Issue by TedDriggs** [xobotyi/react-scrollbars-custom#4]
Native scrolling on iOS Safari applies a momentum effect after the touch is released, but this component currently stops as soon as the touch ends. This makes scrolling feel slower with this component when compared to native behavior.

**Comment by xobotyi** [comment]
Will be implemented in closest update

**Comment by xobotyi** [comment]
1353670bfd0dd73c98c9ceb7bc91da9117765968

Added momentum support, check it please;

**Comment by TedDriggs** [comment]
Beautiful. Thanks for making a great library.
