### ISSUE TITLE
IE support?

### ISSUE THREAD

**Issue by tonypig93** [xobotyi/react-scrollbars-custom#42]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
I can't open demo sites in IE (11, 10, 9), does that mean `react-scrollbars-custom` cannot work in IE? I've tried to use `react-scrollbars-custom` in my project, but it seems not work well in IE: the width of thumb-x is 0 unless I click the track-x, even after I click the track, the width is still incorrect - smaller than it should be. 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of library, and which browser / OS are affected by this issue? Did this work in previous versions of library?**
3.1.5

**Comment by xobotyi** [comment]
Have you tried to configure babel env to target needed IE version (demos not working because i've made to modern target, it'll be fixed in 3.2)?

**Comment by tonypig93** [comment]
I found the causes:
1. the `clientWidth` of `contentEle` is 0 in IE, add `height: 1px` can fix it.
2. IE 9 only supports `-ms-transform`, which should be written as `msTransform` in the `style` property in the `thumb` element.

**Comment by zyke7** [comment]
Cannot open the demo link in IE 11. Getting "Syntax error" in console same as when I tried adding it to my project.
