### ISSUE TITLE
Dom CSS is not a function using enzyme's mount

### ISSUE THREAD

**Issue by JoaoSalles** [xobotyi/react-scrollbars-custom#43]
**Do you want to request a *feature* or report a *bug*?**
Report a bug
**What is the current behavior?**

I am trying to test the component with the enzyme's mount but it returns the following error:

`TypeError: (0 , _domCss2.default) is not a function`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

```
import { mount } from 'enzyme';

const mountSubject = () =>
	mount(<React.Fragment>
				<div className="hierarchy-tree-selection-wrapper">
					<Scrollbar
						autoHide={true}
						autoHideTimeout={1000}
						autoHideDuration={200}
						renderThumbHorizontal={this.renderThumb}
						renderThumbVertical={this.renderThumb}
					>
						<div className="hierarchy-tree-selection">{this.files}</div>
					</Scrollbar>
				</div>
			</React.Fragment>
 );

it('should mount hierarchy', () => {
		const renderedComponent = mountSubject();
		const nodes = renderedComponent.find('.component-mode');
		expect(nodes.length).toEqual(12);
	});
```

**What is the expected behavior?**
Mount the component

**Which versions of library, and which browser / OS are affected by this issue? Did this work in previous versions of library?**

react-scrollbars-custom: 3.1.5. I am running it with Jest. I tried to downgrade versions but does not worked.

**Comment by xobotyi** [comment]
First of all - react-scrollbars-custom does not have any of props you are passing.
Second were does error pointing? Any stack trace?

**Comment by JoaoSalles** [comment]
Sorry, I just migrated from _react-custom-scrollbars_, which had these props. The test is not breaking anymore, I got mislead in the import time.
