### ISSUE TITLE
IE Issue.

### ISSUE THREAD

**Issue by zyke7** [xobotyi/react-scrollbars-custom#47]
Cannot open the demo link in IE 11. Getting "Syntax error" in console same as when I tried adding it to my project.

![ie_issue](https://user-images.githubusercontent.com/46996057/55151726-e154d480-5174-11e9-8c29-143259f43a6c.PNG)

**Comment by xobotyi** [comment]
Demo page has been built with the target of chrome 58, and it is higher than ie11.
Demo for v4 will be built for ie11.

About your project - what version it was?

**Comment by zyke7** [comment]
v4.0.0-alpha.8

**Comment by xobotyi** [comment]
@zyke7 it was a bug related to [cnbuilder](https://github.com/xobotyi/cnbuilder)'s dist package, i've fixed it - so `4.0.0-alpha.9` should work fine.

**Comment by zyke7** [comment]
That seems to have fixed the issue. Thank you for the quick response.

**Comment by zyke7** [comment]
On resizing the container when there is no scroll the track and thumb gets hidden but on reverting the thumb still has a "display: 'none'" on it's inline. This happens only in IE, works fine in chrome. I can add this as a new issue so that you can close this one.

**Comment by xobotyi** [comment]
Sure, make a new one pls
