### ISSUE TITLE
Thumb hidden on resize.

### ISSUE THREAD

**Issue by zyke7** [xobotyi/react-scrollbars-custom#48]
On resizing the container when there is no scroll the track and thumb gets hidden but on reverting the thumb still has a "display: 'none'" on it's inline. This happens only in IE, works fine in chrome.

**Comment by rvillalba-novetta** [comment]
It seems like this is coming from:
https://github.com/xobotyi/react-scrollbars-custom/blob/master/src/Scrollbar.tsx#L956
Changing it to this.thumbYElement.style.display = ""; seems to have done the trick for me on IE.

**Comment by xobotyi** [comment]
@rvillalba-novetta I've came up with same result, today will publish alpha18 with that fix.
