### ISSUE TITLE
Horizontal scrollbar wrong position

### ISSUE THREAD

**Issue by kyndeyrn** [xobotyi/react-scrollbars-custom#49]
I created a container div that contains a number of elements wrapped by <Scrollbar /> and has to be scrolled horizontally.

It works fine on google chrome (mobile/laptop), but on safari (laptop + mobile ios12) the horizontal scrollbar starts in the middle which makes the scroll feel off.

In both images, the scroll is at the very left (the start).
 Chrome:
![image](https://user-images.githubusercontent.com/41577831/55631172-b3484380-57b7-11e9-9a42-862973082c63.png)

Safari:
<img width="494" alt="bug safari" src="https://user-images.githubusercontent.com/41577831/55631309-0b7f4580-57b8-11e9-94e2-958953d18d6a.png">

Clicking on the scrollbar (not the thumb) scrolls to the right position in the container.
Clicking on the srollbar thumb to drag (or on mobile, using finger to scroll) moves weirdly. The scrollbar thumb halves because it seems to think we're in the middle the second I move a bit to the left or right.

**Comment by xobotyi** [comment]
Pretty weird. Acts like it think that we're in RTL mode =\

**Comment by xobotyi** [comment]
What the version?

**Comment by xobotyi** [comment]
fixed in v4.0.0-alpha.11

**Comment by xobotyi** [comment]
Suppose the fastest fix yet:D

**Comment by kyndeyrn** [comment]
Thanks for the quick fix :)

**Comment by xobotyi** [comment]
@kyndeyrn have you tested? Can i close the issue?

**Comment by kyndeyrn** [comment]
@xobotyi I've tested it and it works fine now. thanks!
