### ISSUE TITLE
Missing prop-types as a peerDependency

### ISSUE THREAD

**Issue by KubaJastrz** [xobotyi/react-scrollbars-custom#5]
I wanted to check [bundle size](https://bundlephobia.com/result?p=react-scrollbars-custom), but I'm unable to. You have correctly added `react` and `react-dom`, so maybe you could fix this with a proper `prop-types` version too.

**Comment by xobotyi** [comment]
Will be fixed in closest update;

**Comment by xobotyi** [comment]
Fixed: https://github.com/xobotyi/react-scrollbars-custom/commit/dd5a1fb543e654e4ef6d13a72aa151ef7e562009
