### ISSUE TITLE
Some props error as not existing

### ISSUE THREAD

**Issue by alexpaxton** [xobotyi/react-scrollbars-custom#50]
<img width="836" alt="Screen Shot 2019-04-05 at 11 57 06 AM" src="https://user-images.githubusercontent.com/2433762/55650559-e16b5a80-579a-11e9-9442-b435dfd3b0af.png">

The props I am having trouble with are:

`ScrollToTop` (is this the same as `scrollTop`?)
`ScrollToBottom`
`onScrollStop` (is apparently called `onScrollEnd` mismatch in docs)
`wrapperRenderer`
`trackYRenderer`
`trackXRenderer`
`thumbYRenderer`
`thumbXRenderer`
`contentRenderer`

**Comment by xobotyi** [comment]
You have to read the docs on the dev-master (because it looks like you are using v4.0.0-alpha.xx)

**Comment by libr0s** [comment]
I encounter the same issue in `4.0.0-alpha.12` version.
Temporarily, change to `4.0.0-alpha.10` does the job.

**Comment by xobotyi** [comment]
@libr0s try latest alpha. Looks like inferring props break the ide's props assistance, so I've rolled back propTypes typing.

**Comment by xobotyi** [comment]
Absolutely fixed in v4.0.0-alpha.15
