### ISSUE TITLE
Changes between 4.0 and 3.1.5

### ISSUE THREAD

**Issue by kkotelczuk** [xobotyi/react-scrollbars-custom#51]
What is major changes between versions 4.x.x-alpha and 3.x.x

**Comment by xobotyi** [comment]
Whole component been rewritten from cratch in typescript, a lot of optimisations an performance improvements.
Distributive package now build with rollup.js so it is available with both, esm and cjs modules.

To fully release 4.x.x it si left to write a changelog and make new demo page, but i'm facing extremely lack of fre time =(

**Comment by kkotelczuk** [comment]
So, can we assume that we can use 4.x safety right now, or it's better to use 3.x on production?

**Comment by xobotyi** [comment]
Yes, the component is stable and production-safe now (at least i'm using it with no problems atm), most bugs are fixed.
Some issues with ts-generated propTypes, but it only bother at development stage (due to props hinting not working=\)

**Comment by kkotelczuk** [comment]
Ok, thanks 👍
