### ISSUE TITLE
ScrollEnd event bug

### ISSUE THREAD

**Issue by jmarceli** [xobotyi/react-scrollbars-custom#54]
Thanks for this great library.
I found a small bug with `onScrollEnd` handling, it looks like component is awaiting "scrollEnd" event but "scrollStop" is actually triggered.
Here are the exact lines:
https://github.com/xobotyi/react-scrollbars-custom/blob/dev-master/src/Scrollbar.tsx#L285
and
https://github.com/xobotyi/react-scrollbars-custom/blob/dev-master/src/Scrollbar.tsx#L966

I've made a PR with fix for that issue https://github.com/xobotyi/react-scrollbars-custom/pull/53

**Comment by xobotyi** [comment]
🤦‍♂️I'm an idiot🙈

Sorry missunderstood the diff (had a really hard week🤤) ofcourse I agree that everything should be named `scrollStop` (both event and callback prop), could you please revert first thing you've made?

Really sorry, again🙏

**Comment by jmarceli** [comment]
Done
