### ISSUE TITLE
Live usage example

### ISSUE THREAD

**Issue by jmarceli** [xobotyi/react-scrollbars-custom#55]
Hi, despite documentation in README it is always nice to have some live example. I know about [DEMO](https://xobotyi.github.io/react-scrollbars-custom/) but I don't know any easy way to view React source code, so I've made a minimal example based on your testbench code and my current knowledge.

https://codesandbox.io/s/38k0kxmp75

Feel free to improve it, add it to the README, or ignore this idea. Ideally, I would like to have DEMO page sources to check how to implement presented features.

**Comment by xobotyi** [comment]
Cureent demo page is hardly outdated (even comparing to latest V3).
I've planned to make new demo for V4 with embedded code examples and other stuff, but issuing extremely lack of free time to make it atm (this one and  changenotes are only things that stopping me to release V4)

**Comment by jmarceli** [comment]
Thanks for the example
