### ISSUE TITLE
[v4] Missing wrapper element with display: inline-block

### ISSUE THREAD

**Issue by jmarceli** [xobotyi/react-scrollbars-custom#56]
Please correct me if I'm wrong but based on the [official demo](https://xobotyi.github.io/react-scrollbars-custom/) and my [own example](https://codesandbox.io/s/38k0kxmp75) I see that there is a need for one more wrapper element with `display: inline-block` style. Without that missing element, content seems to not respect the padding-right style on the absolutely positioned parent element.

Here is my fixed example:
https://codesandbox.io/s/1wrx623273

Before fix (current state):
<img width="139" alt="Screen Shot 2019-04-29 at 10 39 38" src="https://user-images.githubusercontent.com/4281333/56884846-4436d580-6a6b-11e9-8179-7405f9f99c7b.png">

With additional wrapper:
<img width="157" alt="Screen Shot 2019-04-29 at 10 40 06" src="https://user-images.githubusercontent.com/4281333/56884849-46009900-6a6b-11e9-9526-18b02f238bf5.png">

This wrapper element might be a part of a library as it won't work correctly without it. Please tell me what do you think about that idea.

**Comment by xobotyi** [comment]
Fixed with v4.0.0-alpha.15
