### ISSUE TITLE
Use overflow: auto instead of scroll

### ISSUE THREAD

**Issue by KubaJastrz** [xobotyi/react-scrollbars-custom#6]
`overflow: scroll` forces the default scrollbar to be visible at all times, while `overflow: auto` only shows it when needed.

Too few items to fill whole area:
![screenshot_20181018_103703](https://user-images.githubusercontent.com/6443113/47142028-46e98e80-d2c2-11e8-91b7-e5763596500d.png)

Enough items to fill the area:
![screenshot_20181018_103732](https://user-images.githubusercontent.com/6443113/47142005-39340900-d2c2-11e8-8767-a612c7bdc6be.png)

Markup:
```jsx
<div className="container">
    <Scrollbar style={{ width: '100%', height: '100%', minHeight: 80 }}>
        {...items}
    </Scrollbar>
</div>
```
Styles:
```css
.container {
    width: 300px;
    height: 300px;
}
```

**Comment by xobotyi** [comment]
Known, working on it right now.

**Comment by xobotyi** [comment]
Fixed: https://github.com/xobotyi/react-scrollbars-custom/commit/996d7c9932525ab6cc947fb8d0903c25494aa4b3
