### ISSUE TITLE
Warning 

### ISSUE THREAD

**Issue by boetn** [xobotyi/react-scrollbars-custom#63]
Hi,

I get the following warning with the latest alpha (17): 

`Warning: React does not recognize the `compensateScrollbarsWidth` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `compensatescrollbarswidth` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

In version v4.0.0alpha13 i did not get this error. Dit anything change?

This is the implementation i'm using:

```javascript
<Scrollbar
   style={{width: '100%', height: '100%'}}
   ref={ref=>{this.scrollbar = ref}} 
   noScrollX
   trackYProps={{
         renderer: props => {
                    const { elementRef, style, ...restProps } = props;
                     return <div {...restProps} ref={elementRef} style={{...style, width: '5px', top: '3px', height: 'calc(100% - 3px)', background: 'rgba(179, 179, 179, 0.1)'}} />;
         }
   }}
   thumbYProps={{
        renderer: props => {
               const {elementRef, style, ...restProps } = props;
               return <div {...restProps} ref={elementRef} style={{...style, background: 'rgba(0, 0, 0, 0.1)'}} />;
       }
   }}
>
     <Content />
</Scrollbar>```

**Comment by xobotyi** [comment]
Known issue, will be fixed in 3-4 hours.

**Comment by boetn** [comment]
Doing a great job man! No hurries from my side.
