### ISSUE TITLE
Content no longer has size in 4.0.0-alpha

### ISSUE THREAD

**Issue by bz2** [xobotyi/react-scrollbars-custom#65]
After upgrading from `3.1.5` to `4.0.0-alpha.18` content within `<Scrollbars/>` no longer has the size of the container. This squashed a lot of components that were designed to expand to fill the available width, which I worked around by adding:

```js
contentProps={{ style: {'min-width': '100%'} }}
```

Old `ScrollbarsCustom` styles: `position: relative; display: flex;` and flexed children.

New `ScrollbarsCustom` styles: `position: relative; width: 100%; height: 100%;` and `ScrollbarsCustom-Content` styles: `display: inline-block; vertical-align: bottom;` (losing the height and width).

**Comment by xobotyi** [comment]
For the future - please use given issue template.

**Comment by bz2** [comment]
@xobotyi Thanks! Left a comment on the change about one possible tweak.
