### ISSUE TITLE
Props `compensateScrollbarsWidth` is passed to child after 4.0.0-alpha.20 version.

### ISSUE THREAD

**Issue by Anatoool** [xobotyi/react-scrollbars-custom#77]
I have console error when I am trying pass compensateScrollbarsWidth property.

`
<Scrollbar onUpdate={onUpdateScroll} compensateScrollbarsWidth={false}>
        <div className="form-tile-body">
          <div className="form-tile-body__content">{children}</div>
        </div>
      </Scrollbar>
`

![image](https://user-images.githubusercontent.com/34212937/58898255-6388e880-8724-11e9-83b6-d7620294c6ef.png)

I haven't this error in 4.0.0-alpha.20 version.

**Comment by xobotyi** [comment]
1) You are using outdated version.
2) Now that property named `disableTracksWidthCompensation`
