### ISSUE TITLE
Does not scrollTop update when scroll?

### ISSUE THREAD

**Issue by seed-of-apricot** [xobotyi/react-scrollbars-custom#85]
**Do you want to request a _feature_ or report a _bug_?**
Question about the behavior.

**What is the current behavior?**
I have set up the Scrollbar manager with a context enabled in this way:

```ts
import React, { ReactNode, useContext } from 'react';
import ReactScrollbarsCustom, {
  ScrollbarContext,
  Scrollbar
} from 'react-scrollbars-custom';

interface IProps {
  children: ReactNode;
}

const ScrollManager = (props: IProps) => {
  return (
    <ReactScrollbarsCustom
      createContext={true}
      noScrollX={true}
      wrapperProps={{
        renderer: props => {
          const { elementRef, style, ...restProps } = props;
          const { right, bottom, ...restStyles } = style as React.CSSProperties;
          return (
            <span
              {...restProps}
              ref={elementRef}
              style={{ right: 0, bottom: 0, ...restStyles }}
            />
          );
        }
      }}
      trackYProps={{
        renderer: props => {
          const { elementRef, style, ...restProps } = props;
          const { width, right, ...restStyles } = style as React.CSSProperties;
          return (
            <span
              {...restProps}
              ref={elementRef}
              style={{
                width: '6px',
                right: '4px',
                ...restStyles
              }}
            />
          );
        }
      }}
      style={{ width: '100vw', height: '100vh' }}
    >
      {props.children}
    </ReactScrollbarsCustom>
  );
};

export const useScrollManager = () => {
  return useContext(ScrollbarContext).parentScrollbar as Scrollbar;
};

export default ScrollManager;
```

and then use the context

```ts
... // imports

const Descriptions: React.FC = () => {
  const scroll = useScrollManager();
  return (
    <Grid>
      ... // something
      {scroll.clientHeight}
      {scroll.scrollTop}
      ... // something
    </Grid>
  )
};
```

The `scroll.clientHeight` is changed whenever I change the window size, but the `scroll.scrollTop` will not update its value upon scrolling.

[Sandbox](https://codesandbox.io/s/nostalgic-shape-99k1p)
(In sandbox changing the browser window will not affect the height value. Instead please move up the border between the preview and console until the number of height parameter get hidden and then move down it.)

**What is the expected behavior?**

How do I update the "scrollTop" for further use, for example loading a certain content at some Y position or stop/start animation?

**Which versions of `react-scrollbars-custom`, React, and which browser / OS are affected by this issue? Did this work in previous versions of `react-scrollbars-custom`?**

react: 16.8.6
react-scrollbars-custom: 4.0.5
OS: Win10
Browser: Opera 63.0.3340.0

**Comment by xobotyi** [comment]
Your content did noit overflow the parent, so there were no scrolling.
Played a bit: https://codesandbox.io/s/prod-dust-4rj8t

**Comment by seed-of-apricot** [comment]
Aw it was my bad when I made the sandbox.
In my project it has more than the client height.

But, now both the `scrollTop` and `clientHeight` won't be changed in your sandbox...?

**Comment by xobotyi** [comment]
@seed-of-apricot updated the sandbox.
Values hast been updated because your component been rendered once and never updated later.

You have to make stateful component and update via any available ways to make it update displayed values;

**Comment by seed-of-apricot** [comment]
Working now, awesome!
That's the use case of the eventEmitter, which I didn't know.

Thank you so much for your help.

**Comment by KirillSkomarovskiy** [comment]
> Your content did noit overflow the parent, so there were no scrolling.
> Played a bit: https://codesandbox.io/s/prod-dust-4rj8t

@xobotyi Hi, could you post an example from this code sandbox?

**Comment by xobotyi** [comment]
@KirillSkomarovskiy nope, have no ide what was there, but it was a fault of developer.
Scrollbar contents was smaller than container therefore had no scrollbars (he forgot to set the state).
