### ISSUE TITLE
vertical scrollbar not visible when inner child has `absolute` and `bottom` styles.

### ISSUE THREAD

**Issue by gencer** [xobotyi/react-scrollbars-custom#86]
**Do you want to request a _feature_ or report a _bug_?**
Bug, maybe feature

**What is the current behavior?**

Scrollbars are hidden when `bottom: 0` given to the  children.

See live demo here. First scrollbar element has `bottom: 0` and second one has not:
https://codesandbox.io/s/rsc-live-example-wdcr0?fontsize=14

**What is the expected behavior?**
Scrollbar should be visible.

**Which versions of `react-scrollbars-custom`, React, and which browser / OS are affected by this issue? Did this work in previous versions of `react-scrollbars-custom`?**

Latest version of this extension and Chrome 75 on Windows 10 1903

You may ask *Why do you gave `bottom` and also `position: absolute`*. Because im creating a chat window. Each message start at bottom and grow to the top. Just like WhatsApp or facebook. So I need to align them to bottom when I add more messages it will grow to the top. To achieve this, I give `absolute` to the message-container in scrollbar. And height should be auto so that it should be shrink to message size. (If i give 100% height then message sticks to the top again.)

**Comment by xobotyi** [comment]
And it sould not have, because your content is absolutely positioned so it is torn out of the parent's rendering context and won't stretch it.
This component does not change browsers scrolling behavior, so if there is no scrollbars - they shouldnt be there browserwise (even with native scrollbars).

Use flexbox or any other approach to reverse content upside-down

**Comment by xobotyi** [comment]
4ex: https://codesandbox.io/s/rsc-live-example-s7pvg

**Comment by gencer** [comment]
@xobotyi, thank you for the example. It did worked very well.

Closing this issue.
