### ISSUE TITLE
TypeError: Cannot read property 'appendChild'

### ISSUE THREAD

**Issue by gregbia** [xobotyi/react-scrollbars-custom#88]
**Do you want to request a _feature_ or report a _bug_?**
Report a bug

**What is the current behavior?**

I am getting the following message in the console:

> Uncaught TypeError: Cannot read property 'appendChild' of null
>     at shouldReverseRTLScroll (index.js:785)
>     at Module.eval (index.js:1050)
>     at eval (index.js:2022)
>     at Module../node_modules/react-scrollbars-custom/dist/esm/index.js (build-premium.js?ver=1561205697:517)
>     at __webpack_require__ (build.js?ver=1561205697:20)
>     at eval (carousel-block.js:12)
>     at Module../assets/src/my-app/my-app.js (build.js?ver=1561205697:108)
>     at __webpack_require__ (build.js?ver=1561205697:20)
>     at eval (index.premium.js:2)
>     at Module../assets/src/index.js (build.js?ver=1561205697:167)
> 

My app code:

```
import Scrollbar from 'react-scrollbars-custom';

//...

return (
  <Scrollbar noScrollY={ true } noScrollX={ hideScroll } style={{ width: "100%", height: "80px" }}>
    // some content
  </Scrollbar>
);

//...
```

I also tried using `<RSC>`. In the documentation `<Scrollbar>` is used but the live demo uses `<RSC>`. Not sure if it matters. 

My modules export config in webpack:

```
    // Config 
    {
        entry: "./assets/src/index.js",
        output: {
            path: path.resolve(__dirname, "./assets/dist"),
            filename: "build.js"
        },
        plugins: [
            new MiniCssExtractPlugin({
                filename: "style.css",
            })
        ],
        module: {
            rules: [{
                    test: /\.(js|jsx)$/,
                    exclude: /node_modules/,
                    loader: "babel-loader"
                },
                {
                    test: /\.view.scss$/,
                    use: [
                        MiniCssExtractPlugin.loader,
                        "css-loader", // translates CSS into CommonJS
                        "sass-loader" // compiles Sass to CSS, using Node Sass by default
                    ]
                },
                {
                    test: /\.editor.scss$/,
                    use: [
                        "style-loader",
                        "css-loader",
                        "sass-loader"
                    ]
                }
            ]
        },
        stats: {
            colors: true
        },
        externals: {
            react: "React",
            'react-dom': 'ReactDOM'
        }
    },
```

My dev dependencies in package:

```
"devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/preset-env": "^7.4.5",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.6",
    "classnames": "^2.2.6",
    "css-loader": "^2.1.0",
    "generate-template-files": "^2.1.0",
    "memize": "^1.0.5",
    "mini-css-extract-plugin": "^0.5.0",
    "node-sass": "^4.12.0",
    "react-scrollbars-custom": "^4.0.5",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.23.1",
    "webpack": "^4.35.0",
    "webpack-cli": "^3.3.4"
  }
```

**Which versions of `react-scrollbars-custom`, React, and which browser / OS are affected by this issue? Did this work in previous versions of `react-scrollbars-custom`?**

react-scrollbars-custom@4.0.5, React 16.8, Chrome, Mac OS.

**Comment by xobotyi** [comment]
RSC/Scrollbars - does not matter, component exported both named and default, so it is just as you name it in your code.

Just to ensure - dont you use an SSR?
Try manually change the row 780 in `dist/cjs/index.js`
From `doc.body.appendChild(el);` to `doc.body.insertBefore(el,null);`
