### ISSUE TITLE
Override Scroller

### ISSUE THREAD

**Issue by Artur93gev** [xobotyi/react-scrollbars-custom#89]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
 React does not recognize the `scrollerProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `scrollerprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**If current behavior is a bug, please provide the steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have extra dependencies other than `react-scrollbars-custom`. Paste the link to your [JSFiddle](https://jsfiddle.net) or [CodeSandbox](https://codesandbox.io) example below:**
https://codesandbox.io/s/hopeful-keller-oz4hq
**What is the expected behavior?**
Prop must not be applied to div itself

**Which versions of `react-scrollbars-custom`, React, and which browser / OS are affected by this issue? Did this work in previous versions of `react-scrollbars-custom`?**
4.0.5

**Comment by Artur93gev** [comment]
The codeSandbox is clearing log. actually its not visible now,  but you can just copy and past the code

**Comment by xobotyi** [comment]
Even on local testbench copypasted your example i have no errors.

**Comment by Artur93gev** [comment]
The issue was with overriding all fields that I can. When all the fields were passes to `react-scrollbars-custom`, the error above was throwing

**Comment by xobotyi** [comment]
@Artur93gev was? Now it's gone?

**Comment by Artur93gev** [comment]
I have tried another solution. So now I 'm not facing the issue. But in computer sceince, nothing happens randomly, So I think the bug exists. You can try to check it out yourself

**Comment by xobotyi** [comment]
@Artur93gev I've tried your example, no errors..

**Comment by xobotyi** [comment]
There is absolutely no way for `scrollerProps` to leak to the div.
As is think - you've acidetially passed this prop somewhere else than root RSC props.

**Comment by xobotyi** [comment]
@Artur93gev Could you please provide any error emitting example?
Otherwise i'll close this bug in the end of next week.
