### ISSUE TITLE
Doesn't work in Edge

### ISSUE THREAD

**Issue by josh-stevens** [xobotyi/react-scrollbars-custom#95]
I think this was previously working in Edge, but it seems something has changed in a build lately. The imported module from this package now includes an object spread on props, which doesn't work in Edge. It throws "SCRIPT1028: Expected identifier, string or number."

That was something discovered earlier this morning. More recently this afternoon, this module actually started causing my build to fail with "ERROR in ./node_modules/react-scrollbars-custom/dist/rsc.mjs 1887:2-11
Can't import the named export 'Component' from non EcmaScript module (only default export is available)." I'm guessing that's from something merged today.

This might be two separate issues, but just wanted to get the author's attention. If you'd like separate issues filed, let me know.

**Comment by josh-stevens** [comment]
I had a hunch that 4.0.5 would be the last working version, since we didn't see any issues with Edge until recently. That seems to be the case. I've pinned our project to use 4.0.5 for now.

**Comment by xobotyi** [comment]
Since `v4.0.10` there is no more `is-fun` and `is-number` packages dependencies, it was a bad idea (actually not really bad, just.. not good one).
The problem with IE was related to `v4.0.10` where i decided to put the untranspiled version to the esm package

**Comment by xobotyi** [comment]
@josh-stevens v4.0.12 supposed to fix this one, recheck pls;

**Comment by josh-stevens** [comment]
Thanks for the quick response. Can confirm that 4.0.12 works in Edge
