### ISSUE TITLE
v4.0.11 Import Breaks in NextJS

### ISSUE THREAD

**Issue by tim-soft** [xobotyi/react-scrollbars-custom#96]
**What is the current behavior?**
Upgrading to the latest `react-scrollbars-custom@4.0.11` yields this error in Next.js
```bash
[ error ] ./node_modules/react-scrollbars-custom/dist/rsc.next.mjs
Can't import the named export 'Component' from non EcmaScript module (only default export is available)
```

#### NextJS is weird in codesandbox, so here's how to repro

```bash
yarn create next-app test-app

cd test-app

yarn add react-scrollbars-custom@4.0.11
```

#### Add Scrollbars to `/pages/index.js`
```js
import Scrollbars from 'react-scrollbars-custom';
```

#### Run the app
```bash
yarn dev
```

**Comment by josh-stevens** [comment]
Yep, was seeing this same issue in https://github.com/xobotyi/react-scrollbars-custom/issues/95. That issue also pointed out that this package doesn't work in Edge anymore, I'm currently rolling back this package to find a version that does work.

**Comment by xobotyi** [comment]
I'm actually very confused... It does both, default and named exports >_>

```javascript
export default Scrollbar;
export { Scrollbar, ScrollbarContext };
```

**Comment by xobotyi** [comment]
okay.. looks like it is node's `.mjs` related stuff, have to roll back to `.js` files now.

**Comment by xobotyi** [comment]
@tim-soft @josh-stevens v4.0.12 supposed to fix this one.
Recheck pls.

**Comment by tim-soft** [comment]
@xobotyi LGTM
